source_dir: source_en
public_dir: public_en
language: en
title: My English Blog
theme: next
description: ''

url: https://lidyaqf.github.io
root: /ening/

theme_config:
  language: en
  menu:
    home: /ening/ || fa fa-home
    categories: /ening/categories/ || fa fa-th
    archives: /ening/archives/ || fa fa-archive
    中文: ../ || fa fa-language
